on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          rm web/TODO.md
          git add -A
          git commit -m "update"
          git push origin main-test --force
